# Generated by Django 4.1.4 on 2023-01-01 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lister", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="listers",
            field=models.ManyToManyField(
                through="lister.ConnectedLister", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
