# Generated by Django 4.1.4 on 2023-01-01 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lister", "0001_initial"),
        ("account", "0002_user_listers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="listers",
            field=models.ManyToManyField(
                blank=True,
                through="lister.ConnectedLister",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
