# Generated by Django 4.1.3 on 2022-11-30 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.MinLengthValidator(
                        6, message="password length MUST be 6 characters or more"
                    )
                ],
            ),
        ),
    ]
