# Generated by Django 4.1.3 on 2022-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0003_user_is_email_verified_user_is_phone_number_verified_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
