# Generated by Django 4.1.3 on 2022-11-30 04:06

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                unique=True,
                validators=[account.validators.validate_username],
                verbose_name="username",
            ),
        ),
    ]
