# Generated by Django 4.1.4 on 2023-01-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_listers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="listers",
        ),
    ]
