# Generated by Django 4.1.3 on 2022-12-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasklist", "0002_remove_tasklist_notification_senttasklisttask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senttasklisttask",
            name="tasklist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasklist.senttasklist"
            ),
        ),
    ]
