# Generated by Django 4.1.3 on 2022-12-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasklist", "0003_alter_senttasklisttask_tasklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="senttasklist",
            name="tasks_num",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasklist",
            name="tasks_num",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
