# Generated by Django 4.1.3 on 2022-12-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasklist", "0004_senttasklist_tasks_num_tasklist_tasks_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="senttasklist",
            name="notification",
        ),
        migrations.AddField(
            model_name="senttasklist",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
    ]
