# Generated by Django 4.1.3 on 2022-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasklist", "0005_remove_senttasklist_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="id",
            field=models.PositiveBigIntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
