# Generated by Django 4.1.4 on 2023-01-01 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                ("due", models.DateTimeField(blank=True, null=True)),
                ("repeat", models.BooleanField(default=False)),
                (
                    "repeat_frequency",
                    models.CharField(
                        choices=[("D", "Daily"), ("W", "Weekly"), ("M", "Monthly")],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
