# Generated by Django 4.1.3 on 2022-12-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="due",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
