# Generated by Django 4.1.3 on 2022-12-03 01:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lister", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connectionrequest",
            unique_together={("sender", "receiver")},
        ),
    ]
