# Generated by Django 4.1.4 on 2022-12-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lister", "0002_alter_connectedlisters_listers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connectionrequest",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="connectionrequest",
            constraint=models.UniqueConstraint(
                fields=("sender", "receiver"), name="unique_request"
            ),
        ),
    ]
