# Generated by Django 4.1.4 on 2022-12-19 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taskgroup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskgroup",
            name="members",
            field=models.ManyToManyField(
                related_name="member", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
