# Generated by Django 4.1.4 on 2023-01-03 00:49

from django.conf import settings
from django.db import migrations, models
import taskgroup.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taskgroup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskgrouptask",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="taskgroup",
            name="creator",
            field=models.ForeignKey(
                on_delete=models.SET(taskgroup.models.get_sentinel_user),
                related_name="taskgroup_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskgrouptask",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(taskgroup.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskgrouptask",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.SET(taskgroup.models.get_sentinel_user),
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
