# Generated by Django 4.1.4 on 2022-12-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskgroup", "0002_alter_taskgrouptask_completed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskgrouptask",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskgrouptask",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
