# Generated by Django 4.1.4 on 2023-01-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskgroup", "0002_taskgrouptask_edited_alter_taskgroup_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskgrouptask",
            name="last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
